### ISSUE TITLE
How do i test that

### ISSUE THREAD

**Issue by ayoubserti** [OELBOUHASSANI/anyToWakDB#1]
Hi, 
How can i test that? Do i need any specific config?

**Comment by OELBOUHASSANI** [comment]
Hello @ayoubserti  
Just create a wakanda solution then copy the module to backend/modules , make a remote connexion to any remote supported by wakanda for example MySQL. name it for example remote , require the module in any ssjs file .

var anyToWakDB =require('anyToWakDB')
anyToWakDB.allToWakandaDB("remote","wakDBFromRemote") ;

the migration is done  :)

**Comment by ayoubserti** [comment]
Ok thank you a lot.
